# Generated by Django 5.1.6 on 2025-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0004_image_alter_otptoken_otp_code_delete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='3a6e2b', max_length=6),
        ),
    ]
