# Generated by Django 5.1.6 on 2025-04-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0005_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='bdbbc5', max_length=6),
        ),
    ]
