# Generated by Django 5.1.6 on 2025-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0010_alter_otptoken_otp_code_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('MobNumber', models.CharField(default='', max_length=15)),
                ('collage', models.CharField(choices=[('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('tiba', 'TIBA'), ('coed', 'COED'), ('social', 'SOCIAL')], default='', max_length=50)),
                ('yearOfStudy', models.CharField(choices=[('first year', 'First  year'), ('second year', 'Second year'), ('third year', 'Third year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth year'), ('masters', 'Masters')], default='', max_length=20)),
                ('churchName', models.CharField(choices=[('udom central CIVE', 'UDOM CENTRAL CIVE'), ('udom east TIBA', 'UDOM EAST TIBA'), ('udom east COED', 'UDOM EAST COED'), ('udom west SOCIAL', 'UDOM WEST SOCIAL'), ('udom west HUMANITIES', 'UDOM WEST HUMANITIES')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='', max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='user_images/%Y/%m/%d/')),
                ('nameOfAnEvent', models.CharField(default='', max_length=50)),
                ('costUsed', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('contributionType', models.CharField(choices=[('miradi', 'Miradi'), ('vyeti', 'Vyeti'), ('ada', 'Ada'), ('michango mingine', 'Michango mingine')], max_length=100)),
                ('month', models.DateField()),
                ('AmountPaid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/%Y/%m/%d/')),
                ('yearOfStudy', models.CharField(choices=[('first year', 'First  year'), ('second year', 'Second year'), ('third year', 'Third year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth year'), ('masters', 'Masters')], default='', max_length=100)),
                ('certificateStatus', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('on process', 'On process')], default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='316473', max_length=6),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='church',
            field=models.CharField(choices=[('Ntyuka', 'Ntyuka'), ('Social', 'Social'), ('ngongona', 'Ngongona'), ('msangalalee', 'Msangalalee')], max_length=50),
        ),
    ]
