# Generated by Django 5.1.6 on 2025-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0012_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='churchName',
            field=models.CharField(choices=[('select church', 'Select church'), ('udom central CIVE', 'UDOM CENTRAL CIVE'), ('udom east TIBA', 'UDOM EAST TIBA'), ('udom east COED', 'UDOM EAST COED'), ('udom west SOCIAL', 'UDOM WEST SOCIAL'), ('udom west HUMANITIES', 'UDOM WEST HUMANITIES')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='collage',
            field=models.CharField(choices=[('choose collage', 'Choose collage'), ('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('tiba', 'TIBA'), ('coed', 'COED'), ('social', 'SOCIAL')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='yearOfStudy',
            field=models.CharField(choices=[('choose year of study', 'Choose year of study'), ('first year', 'First  year'), ('second year', 'Second year'), ('third year', 'Third year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth year'), ('masters', 'Masters')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c41cc1', max_length=6),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='contributionType',
            field=models.CharField(choices=[('choose contribution type', 'Choose contribution type'), ('miradi', 'Miradi'), ('vyeti', 'Vyeti'), ('ada', 'Ada'), ('michango mingine', 'Michango mingine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='zonehistory',
            name='yearOfStudy',
            field=models.CharField(choices=[('choose year of study', 'Choose year of study'), ('first year', 'First  year'), ('second year', 'Second year'), ('third year', 'Third year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth year'), ('masters', 'Masters')], default='', max_length=100),
        ),
    ]
