# Generated by Django 5.1.6 on 2025-04-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0013_alter_allmembers_churchname_alter_allmembers_collage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('established_date', models.DateField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='treasurer',
            name='collage',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5bee62', max_length=6),
        ),
        migrations.CreateModel(
            name='MonthlyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_payment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accounts', to='ootp.ventures')),
            ],
        ),
        migrations.CreateModel(
            name='MainPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_plans', to='ootp.ventures')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('leader_email', models.EmailField(max_length=254)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_credentials', to='ootp.ventures')),
            ],
        ),
    ]
