# Generated by Django 5.1.6 on 2025-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0014_ventures_treasurer_collage_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainplans',
            old_name='price_per_month',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='leadercredentials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='leadercredentials',
            name='leaderMobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='monthlyaccount',
            name='monthlyCost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyaccount',
            name='monthlyGain',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyaccount',
            name='monthlyProfit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='116cb1', max_length=6),
        ),
    ]
