# Generated by Django 5.1.6 on 2025-04-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0015_rename_price_per_month_mainplans_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalMissionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mission_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='37486d', max_length=6),
        ),
        migrations.CreateModel(
            name='HealthStatusOfMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('health_condition', models.TextField()),
                ('treatment_administered', models.TextField()),
                ('username', models.CharField(default='', max_length=50)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('member_collage', models.CharField(choices=[('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('social', 'SOCIAL'), ('coed', 'COED'), ('cnms', 'CNMS'), ('coese', 'COESE'), ('cobe', 'COBE')], default='', max_length=50)),
                ('follow_up_date', models.DateField()),
                ('medical_missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='ootp.medicalmissionary')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_Image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('output_raised', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('medical_missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='ootp.medicalmissionary')),
            ],
        ),
    ]
