# Generated by Django 5.1.6 on 2025-04-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0016_medicalmissionary_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('established_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b9609e', max_length=6),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquired_date', models.DateField()),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ootp.communication')),
            ],
        ),
        migrations.CreateModel(
            name='MainGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=255)),
                ('goal_description', models.TextField()),
                ('achieved', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=8, max_digits=12)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_goals', to='ootp.communication')),
            ],
        ),
        migrations.CreateModel(
            name='TreasurerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ootp.treasurer')),
            ],
        ),
        migrations.CreateModel(
            name='TreasurerAmountUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aim', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_used', to='ootp.treasurer')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='ootp.treasurergoal')),
            ],
        ),
        migrations.CreateModel(
            name='TreasurerAmountCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_collected', to='ootp.treasurer')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='ootp.treasurergoal')),
            ],
        ),
    ]
