# Generated by Django 5.1.6 on 2025-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0017_communication_alter_otptoken_otp_code_assets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasurerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('contributionType', models.CharField(choices=[('choose contribution type', 'Choose contribution type'), ('miradi', 'Miradi'), ('vyeti', 'Vyeti'), ('ada', 'Ada'), ('michango mingine', 'Michango mingine')], max_length=100)),
                ('month', models.DateField()),
                ('AmountPaid', models.IntegerField()),
                ('collage', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='treasurer',
            old_name='month',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='treasurer',
            name='AmountPaid',
        ),
        migrations.RemoveField(
            model_name='treasurer',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='treasurer',
            name='contributionType',
        ),
        migrations.RemoveField(
            model_name='treasurer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='treasurer',
            name='username',
        ),
        migrations.AddField(
            model_name='treasurer',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='treasurer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treasurer',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='583a90', max_length=6),
        ),
    ]
