# Generated by Django 5.1.6 on 2025-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0018_treasurerrecords_rename_month_treasurer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0789b9', max_length=6),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='treasurerrecords',
            name='collage',
            field=models.CharField(choices=[('choose collage of member', 'collage of member'), ('choose collage', 'Choose collage'), ('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('tiba', 'TIBA'), ('coed', 'COED'), ('social', 'SOCIAL')], default='', max_length=30),
        ),
    ]
