# Generated by Django 5.1.6 on 2025-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0019_alter_otptoken_otp_code_alter_treasurer_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasureramountcollected',
            name='treasurer',
        ),
        migrations.RemoveField(
            model_name='treasureramountused',
            name='treasurer',
        ),
        migrations.RemoveField(
            model_name='treasurergoal',
            name='treasurer',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fffc79', max_length=6),
        ),
    ]
