# Generated by Django 5.1.6 on 2025-04-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0020_remove_treasureramountcollected_treasurer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalMissionaryEventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionary_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_Image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('output_raised', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalMissionaryHealthStatusOfMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionary_name', models.CharField(max_length=255)),
                ('member_name', models.CharField(max_length=255)),
                ('health_condition', models.TextField()),
                ('treatment_administered', models.TextField()),
                ('username', models.CharField(default='', max_length=50)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('member_collage', models.CharField(choices=[('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('social', 'SOCIAL'), ('coed', 'COED'), ('cnms', 'CNMS'), ('coese', 'COESE'), ('cobe', 'COBE')], default='', max_length=50)),
                ('follow_up_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='healthstatusofmembers',
            name='medical_missionary',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f254f7', max_length=6),
        ),
        migrations.DeleteModel(
            name='EventDetails',
        ),
        migrations.DeleteModel(
            name='HealthStatusOfMembers',
        ),
    ]
