# Generated by Django 5.1.6 on 2025-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0021_medicalmissionaryeventdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalmissionary',
            old_name='name',
            new_name='goal_name',
        ),
        migrations.AddField(
            model_name='medicalmissionary',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2c895a', max_length=6),
        ),
    ]
