# Generated by Django 5.1.6 on 2025-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0022_rename_name_medicalmissionary_goal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenturesLeaderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leaderMobile', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='VenturesMainPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VenturesMonthlyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_payment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('monthlyGain', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('monthlyCost', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('monthlyProfit', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainplans',
            name='venture',
        ),
        migrations.RemoveField(
            model_name='monthlyaccount',
            name='venture',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d475fb', max_length=6),
        ),
        migrations.DeleteModel(
            name='LeaderCredentials',
        ),
        migrations.DeleteModel(
            name='MainPlans',
        ),
        migrations.DeleteModel(
            name='MonthlyAccount',
        ),
    ]
