# Generated by Django 5.1.6 on 2025-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0023_venturesleadercredentials_venturesmainplans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMainGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=255)),
                ('goal_description', models.TextField()),
                ('achieved', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='maingoals',
            name='communication',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7fe9cd', max_length=6),
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='MainGoals',
        ),
    ]
