# Generated by Django 5.1.6 on 2025-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0026_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationleadercredentials',
            name='role',
            field=models.CharField(choices=[('choose role', 'role'), ('staff', 'STAFF'), ('ministry leader', 'MINISTRY LEADER')], max_length=255),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a05024', max_length=6),
        ),
    ]
