# Generated by Django 5.1.6 on 2025-04-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0027_alter_communicationleadercredentials_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('bodyAbility', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNeedsDisabledMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('problem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='specialNeedsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(default='special needs event', max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='specialNeedsMainGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b16aba', max_length=6),
        ),
    ]
