# Generated by Django 5.1.6 on 2025-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0028_specialneeds_specialneedsdisabledmembers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobileNumber', models.IntegerField(default='+255')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('dateJoined', models.DateField()),
                ('collage', models.CharField(choices=[('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('social', 'SOCIAL'), ('coed', 'COED'), ('cnms', 'CNMS'), ('coese', 'COESE'), ('cobe', 'COBE')], default='', max_length=100)),
                ('yearOfStudy', models.CharField(choices=[('choose year of study', 'Choose year of study'), ('first year', 'First  year'), ('second year', 'Second year'), ('third year', 'Third year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth year'), ('masters', 'Masters')], default='', max_length=100)),
                ('program', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='educationLeaderAllMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobileNumber', models.IntegerField(default='+255')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('dateJoined', models.DateField()),
                ('collage', models.CharField(choices=[('cive', 'CIVE'), ('humanities', 'HUMANITIES'), ('social', 'SOCIAL'), ('coed', 'COED'), ('cnms', 'CNMS'), ('coese', 'COESE'), ('cobe', 'COBE')], default='', max_length=100)),
                ('yearOfStudy', models.CharField(choices=[('choose year of study', 'Choose year of study'), ('first year', 'First  year'), ('second year', 'Second year'), ('third year', 'Third year'), ('fourth year', 'Fourth year'), ('fifth year', 'Fifth year'), ('masters', 'Masters')], default='', max_length=100)),
                ('program', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='educationsLeadersGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalName', models.CharField(default='', max_length=100)),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('expression', models.TextField(default='not provided', max_length=400)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('on process', 'on process')], default='completed', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='04a109', max_length=6),
        ),
    ]
