# Generated by Django 5.1.6 on 2025-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0029_educationleader_educationleaderallmembers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e73e34', max_length=6),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='church',
            field=models.CharField(choices=[('Ntyuka', 'Ntyuka'), ('Social', 'Social'), ('ngongona', 'Ngongona'), ('msangalalee', 'Msangalalee'), ('makulu', 'makulu')], max_length=50),
        ),
    ]
