# Generated by Django 5.1.6 on 2025-04-13 19:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0030_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLeaderPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e17a8d', max_length=6),
        ),
    ]
