# Generated by Django 5.1.6 on 2025-04-13 19:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0031_educationleaderposts_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationleadercredentials',
            name='description',
            field=tinymce.models.HTMLField(default='No description'),
        ),
        migrations.AlterField(
            model_name='communicationmaingoals',
            name='goal_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='educationsleadersgoals',
            name='expression',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='medicalmissionary',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='medicalmissionaryeventdetails',
            name='event_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='medicalmissionaryhealthstatusofmembers',
            name='health_condition',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4e2dbb', max_length=6),
        ),
        migrations.AlterField(
            model_name='specialneedsmaingoals',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='description',
            field=tinymce.models.HTMLField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='treasurergoal',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='ventures',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='venturesmainplans',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
