# Generated by Django 5.1.6 on 2025-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0032_alter_communicationleadercredentials_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='26ad58', max_length=6),
        ),
        migrations.AlterField(
            model_name='venturesmonthlyaccount',
            name='monthlyCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venturesmonthlyaccount',
            name='monthlyGain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venturesmonthlyaccount',
            name='monthlyProfit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
