# Generated by Django 5.1.6 on 2025-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0033_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturesmonthlyaccount',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0c5647', max_length=6),
        ),
    ]
