# Generated by Django 5.1.6 on 2025-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0034_venturesmonthlyaccount_name_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturesleadercredentials',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='66a536', max_length=6),
        ),
    ]
