# Generated by Django 5.1.6 on 2025-04-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0035_venturesleadercredentials_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationmaingoals',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='55ae19', max_length=6),
        ),
    ]
