# Generated by Django 5.1.6 on 2025-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0037_treasurergoal_status_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasureramountcollected',
            old_name='amount',
            new_name='amountCollected',
        ),
        migrations.RenameField(
            model_name='treasureramountcollected',
            old_name='date',
            new_name='dateOfCollection',
        ),
        migrations.RemoveField(
            model_name='treasureramountcollected',
            name='goal',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cd226b', max_length=6),
        ),
    ]
