# Generated by Django 5.1.6 on 2025-04-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0038_rename_amount_treasureramountcollected_amountcollected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d51699', max_length=6),
        ),
    ]
