# Generated by Django 5.1.6 on 2025-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0039_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasureramountused',
            old_name='aim',
            new_name='aimOfUse',
        ),
        migrations.RenameField(
            model_name='treasureramountused',
            old_name='amount',
            new_name='amountUsed',
        ),
        migrations.RenameField(
            model_name='treasureramountused',
            old_name='date',
            new_name='dateOfUse',
        ),
        migrations.RemoveField(
            model_name='treasureramountused',
            name='goal',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cfffe0', max_length=6),
        ),
    ]
