# Generated by Django 5.1.6 on 2025-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0040_rename_aim_treasureramountused_aimofuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='43eae2', max_length=6),
        ),
    ]
