# Generated by Django 5.1.6 on 2025-04-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0041_allmembers_image_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=100)),
                ('date_of_event', models.DateField()),
                ('cost_used', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8345d6', max_length=6),
        ),
    ]
