# Generated by Django 5.1.6 on 2025-04-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0042_educationevents_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationFeesDeficitMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=100)),
                ('collage', models.CharField(default='', max_length=100)),
                ('feesStatus', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationOwenedAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetName', models.CharField(default='', max_length=100)),
                ('value', models.IntegerField(default='00', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ad84b0', max_length=6),
        ),
    ]
