# Generated by Django 5.1.6 on 2025-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0043_educationfeesdeficitmembers_educationowenedassets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationowenedassets',
            name='value',
            field=models.IntegerField(default='00'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b4898c', max_length=6),
        ),
    ]
