# Generated by Django 5.1.6 on 2025-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0044_alter_educationowenedassets_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationfeesdeficitmembers',
            name='collage',
            field=models.CharField(choices=[('select collage', 'select collage'), ('cive', 'CIVE'), ('social', 'SOCIAL'), ('tiba', 'TIBA'), ('coed', 'COED'), ('humanity', 'HUMANITIES')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c98163', max_length=6),
        ),
    ]
