# Generated by Django 5.1.6 on 2025-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0045_alter_educationfeesdeficitmembers_collage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationfeesdeficitmembers',
            name='feesStatus',
            field=models.CharField(choices=[('choose status', 'choose status'), ('pending', 'pending'), ('on process', 'on process'), ('completed', 'completed')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ea9310', max_length=6),
        ),
    ]
