# Generated by Django 5.1.6 on 2025-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0046_alter_educationfeesdeficitmembers_feesstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialneedsdisabledmembers',
            name='body_ability_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('partially disabled', 'Partially Disabled'), ('fully disabled', 'Fully Disabled')], default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='specialneedsdisabledmembers',
            name='collage',
            field=models.CharField(choices=[('select collage', 'Select collage'), ('cive', 'CIVE'), ('social', 'SOCIAL'), ('tiba', 'TIBA'), ('coed', 'COED'), ('humanity', 'HUMANITIES')], default='select collage', max_length=100),
        ),
        migrations.AddField(
            model_name='specialneedsdisabledmembers',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specialneedsdisabledmembers',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='specialneedsdisabledmembers',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7268a1', max_length=6),
        ),
        migrations.AlterField(
            model_name='specialneedsdisabledmembers',
            name='problem',
            field=models.CharField(default='', max_length=50),
        ),
    ]
