# Generated by Django 5.1.6 on 2025-04-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootp', '0047_specialneedsdisabledmembers_body_ability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cd2534', max_length=6),
        ),
    ]
